// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL3uQnh2bJL6iGsGnf08D3bI_x0w8RVuM',
    appId: '1:1036593515665:web:38036c14d444b582fa8330',
    messagingSenderId: '1036593515665',
    projectId: 'todo-app-uni',
    authDomain: 'todo-app-uni.firebaseapp.com',
    storageBucket: 'todo-app-uni.firebasestorage.app',
    measurementId: 'G-SERV6B611G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIs3RoMmx3r57Vacn2TO-JIFpKF7Cq6Yw',
    appId: '1:1036593515665:android:bfc4b29e6d62a0e2fa8330',
    messagingSenderId: '1036593515665',
    projectId: 'todo-app-uni',
    storageBucket: 'todo-app-uni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCtGCEBeS8OUg7Z0CpvMbTQ9ymJnqpvH8',
    appId: '1:1036593515665:ios:d9aa9165c94833bffa8330',
    messagingSenderId: '1036593515665',
    projectId: 'todo-app-uni',
    storageBucket: 'todo-app-uni.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCtGCEBeS8OUg7Z0CpvMbTQ9ymJnqpvH8',
    appId: '1:1036593515665:ios:d9aa9165c94833bffa8330',
    messagingSenderId: '1036593515665',
    projectId: 'todo-app-uni',
    storageBucket: 'todo-app-uni.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL3uQnh2bJL6iGsGnf08D3bI_x0w8RVuM',
    appId: '1:1036593515665:web:a776e1423a8a2ea3fa8330',
    messagingSenderId: '1036593515665',
    projectId: 'todo-app-uni',
    authDomain: 'todo-app-uni.firebaseapp.com',
    storageBucket: 'todo-app-uni.firebasestorage.app',
    measurementId: 'G-QJHV6SGDE5',
  );
}
